version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: 
      - .live.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  ytc-backend:
    container_name: ytc-backend-prod
    image: <dockerID>/ytc-backend-prod
    build: 
      context: .
      dockerfile: Dockerfile
    command: python ./drf_jwt_backend/manage/py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - db
      - migration
    depends_on: 
      - migration

  migration:
    container_name: ytc-backend-migration
    image: <dockerID>/ytc-backend-prod
    env_file:
      - .live.env
    command:
      [
        sh,
        -cx,
        "python ./drf_jwt_backend/manage.py migrate && python ./drf_jwt_backend/manage.py createsuperuser --noinput"
      ]
    links:
      - db 
    depends_on:
      - db
      